/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MultiSenderInterface extends Interface {
  getFunction(nameOrSignature: "isClaimed" | "multisend"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BatchComplete"): EventFragment;

  encodeFunctionData(
    functionFragment: "isClaimed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "multisend",
    values: [AddressLike, BigNumberish[], BytesLike[]]
  ): string;

  decodeFunctionResult(functionFragment: "isClaimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multisend", data: BytesLike): Result;
}

export namespace BatchCompleteEvent {
  export type InputTuple = [
    successCount: BigNumberish,
    totalAmount: BigNumberish
  ];
  export type OutputTuple = [successCount: bigint, totalAmount: bigint];
  export interface OutputObject {
    successCount: bigint;
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultiSender extends BaseContract {
  connect(runner?: ContractRunner | null): MultiSender;
  waitForDeployment(): Promise<this>;

  interface: MultiSenderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isClaimed: TypedContractMethod<[index: BigNumberish], [boolean], "view">;

  multisend: TypedContractMethod<
    [token: AddressLike, indices: BigNumberish[], packed: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isClaimed"
  ): TypedContractMethod<[index: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "multisend"
  ): TypedContractMethod<
    [token: AddressLike, indices: BigNumberish[], packed: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BatchComplete"
  ): TypedContractEvent<
    BatchCompleteEvent.InputTuple,
    BatchCompleteEvent.OutputTuple,
    BatchCompleteEvent.OutputObject
  >;

  filters: {
    "BatchComplete(uint256,uint256)": TypedContractEvent<
      BatchCompleteEvent.InputTuple,
      BatchCompleteEvent.OutputTuple,
      BatchCompleteEvent.OutputObject
    >;
    BatchComplete: TypedContractEvent<
      BatchCompleteEvent.InputTuple,
      BatchCompleteEvent.OutputTuple,
      BatchCompleteEvent.OutputObject
    >;
  };
}
